[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
news_quest = "5Whv2g9gDJZnj9nsh2DFgQS9KQek7PZT4CJZeGxB1RxY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "phantom-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
